# Generated by Django 2.1.7 on 2019-03-31 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroentrada',
            name='dataDocumento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
