# Generated by Django 2.1.7 on 2019-04-01 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_livroentrada_datadocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroentrada',
            name='assunto',
            field=models.CharField(max_length=100, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='livroentrada',
            name='classificacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='livroentrada',
            name='documento',
            field=models.FileField(null=True, upload_to='correspondencia/documento', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='livroentrada',
            name='observacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='livroentrada',
            name='proveniencia',
            field=models.CharField(max_length=100, null=True, verbose_name='Proveniência'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='assunto',
            field=models.CharField(max_length=100, null=True, verbose_name='Introduza o assunto do documento'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='classificacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Introduz a classificação'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='data',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Introduza da data de saída do documento'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='destinatario',
            field=models.CharField(max_length=100, null=True, verbose_name='Introduza o destinatário do documento'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='localidade',
            field=models.CharField(max_length=100, null=True, verbose_name='Introduza a localidade do documento'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='observacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Introduza a observacao do documento'),
        ),
        migrations.AddField(
            model_name='livrosaida',
            name='processo',
            field=models.CharField(max_length=50, null=True, verbose_name='Introduza o número do processo'),
        ),
        migrations.AlterField(
            model_name='livroentrada',
            name='dataDocumento',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='livroentrada',
            name='numeroDocumento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='livroentrada',
            name='numeroEntrada',
            field=models.IntegerField(verbose_name='Número de entrada'),
        ),
        migrations.AlterField(
            model_name='livrosaida',
            name='numeroOrdem',
            field=models.CharField(max_length=100, verbose_name='Número de ordem'),
        ),
    ]
